'use strict';
const $=id=>document.getElementById(id), canvas=$('world'),ctx=canvas.getContext('2d',{alpha:false});
// Every open cell is connected; walls define the playable house.
const grid=[
'111111111111111',
'100000100000001',
'100000100000001',
'100000100000001',
'111011111011101',
'100000000000001',
'101110111011101',
'100010100010001',
'100010100010001',
'100000000000001',
'111011101110101',
'100000100000001',
'100000100000001',
'100000000000001',
'111111111111111'];
const objects=[
{id:'t1',x:3.5,y:2.5,type:'tape',name:'Cinta 01 · La llegada',digit:'7',text:'«Llegamos a las <strong>7</strong>. Alguien había puesto la mesa, pero nadie recordaba haber entrado antes. El reloj se detuvo cuando cerramos la puerta.»',hint:'El primer número es la hora de llegada.'},
{id:'t2',x:12.5,y:2.5,type:'tape',name:'Cinta 02 · Los invitados',digit:'3',text:'«En la fotografía solo salimos <strong>3</strong>. Éramos cuatro. La figura del fondo no tiene cara. Y ahora está más cerca que en la primera foto.»',hint:'El segundo número es la cantidad de personas en la foto.'},
{id:'t3',x:2.5,y:12.5,type:'tape',name:'Cinta 03 · La salida',digit:'9',text:'«Lo intentamos <strong>9</strong> veces. La puerta siempre daba al mismo pasillo. La décima vez dejamos de mirar atrás. Primero la llave. Después, los números en el orden de las cintas.»',hint:'El tercer número es la cantidad de intentos fallidos.'},
{id:'key',x:12.5,y:12.5,type:'key',name:'Llave de la entrada'},
{id:'exit',x:7.5,y:1.6,type:'exit',name:'Puerta de salida'},
{id:'note',x:8.5,y:7.5,type:'note',name:'Una nota en la pared'}];
let state='intro',p={x:7.5,y:3.4,a:-Math.PI/2},keys={},collected=new Set(),fear=0,elapsed=0,enemy={x:13.5,y:13.5},path=[],pathClock=0,near=null,toastTime=0,safe=0,explore=false,step=0,last=0,look=null,sound=false,audio=null,ambient=null,gain=null,heartbeat=0;
let W=640,H=400,zbuf=[];const fov=1.05;
const wallPhoto=new Image(),ghostPhoto=new Image();wallPhoto.src='assets/wall.png';ghostPhoto.src='assets/cakelyn.png';const scarePhoto=new Image();scarePhoto.src='assets/cakelyn-scare.png';
let awake=false,chasing=false,chaseLost=0,stamina=100,scareTime=0,scareFatal=false,pendingScare=false,ambushAt=18,musicClock=0,musicBeat=0,footClock=0,master=null,musicBus=null,noiseBuffer=null;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const floorCanvas=document.createElement('canvas');floorCanvas.width=128;floorCanvas.height=128;const fc=floorCanvas.getContext('2d');
const floorPixels=fc.createImageData(128,128);for(let y=0;y<128;y++)for(let x=0;x<128;x++){const i=(y*128+x)*4;const seam=x%32<2||((y+(Math.floor(x/32)%2)*64)%128<2);const grain=Math.sin(y*.65+Math.sin(x*.3)*3)*3+Math.sin(y*2.2+x*.06)*2;const v=seam?12:52+grain+Math.random()*8;floorPixels.data[i]=v*1.15;floorPixels.data[i+1]=v*.91;floorPixels.data[i+2]=v*.65;floorPixels.data[i+3]=255}fc.putImageData(floorPixels,0,0);
let floorFrame;let distractionClock=6,footSide=1,shriekClock=1;
function drawFloor(horizon){if(!floorFrame||floorFrame.width!==W||floorFrame.height!==H)floorFrame=ctx.createImageData(W,H);const data=floorFrame.data;const rayLX=Math.cos(p.a)-Math.sin(p.a)*Math.tan(fov/2),rayLY=Math.sin(p.a)+Math.cos(p.a)*Math.tan(fov/2),rayRX=Math.cos(p.a)+Math.sin(p.a)*Math.tan(fov/2),rayRY=Math.sin(p.a)-Math.cos(p.a)*Math.tan(fov/2);for(let y=Math.ceil(horizon);y<H;y+=2){const dist=H*.4/Math.max(1,y-horizon),light=Math.max(.12,.83/(1+dist*.18));for(let x=0;x<W;x+=2){const wx=p.x+dist*(rayRX+(rayLX-rayRX)*x/W),wy=p.y+dist*(rayRY+(rayLY-rayRY)*x/W),tx=((Math.floor(wx*90)%128)+128)%128,ty=((Math.floor(wy*90)%128)+128)%128,ti=(ty*128+tx)*4;for(let yy=y;yy<Math.min(H,y+2);yy++)for(let xx=x;xx<Math.min(W,x+2);xx++){let i=(yy*W+xx)*4;data[i]=floorPixels.data[ti]*light;data[i+1]=floorPixels.data[ti+1]*light;data[i+2]=floorPixels.data[ti+2]*light;data[i+3]=255}}}ctx.putImageData(floorFrame,0,0,0,Math.ceil(horizon),W,H-Math.ceil(horizon))}

function resize(){W=Math.min(1100,Math.max(480,Math.floor(innerWidth*.8)));H=Math.floor(W*innerHeight/innerWidth);canvas.width=W;canvas.height=H}resize();addEventListener('resize',resize);
function wall(x,y){return grid[Math.floor(y)]?.[Math.floor(x)]!=='0'}
function move(entity,dx,dy,r=.19){if(!wall(entity.x+dx+Math.sign(dx)*r,entity.y-r)&&!wall(entity.x+dx+Math.sign(dx)*r,entity.y+r))entity.x+=dx;if(!wall(entity.x-r,entity.y+dy+Math.sign(dy)*r)&&!wall(entity.x+r,entity.y+dy+Math.sign(dy)*r))entity.y+=dy}
function cast(a){const dx=Math.cos(a),dy=Math.sin(a);let mx=Math.floor(p.x),my=Math.floor(p.y);const ddx=Math.abs(1/dx),ddy=Math.abs(1/dy),sx=dx<0?-1:1,sy=dy<0?-1:1;let tx=(dx<0?p.x-mx:mx+1-p.x)*ddx,ty=(dy<0?p.y-my:my+1-p.y)*ddy,side=0;for(let i=0;i<50;i++){if(tx<ty){tx+=ddx;mx+=sx;side=0}else{ty+=ddy;my+=sy;side=1}if(grid[my]?.[mx]!=='0')break}const d=side?ty-ddy:tx-ddx;return{d,side,u:((side?p.x+d*dx:p.y+d*dy)%1+1)%1,mx,my}}
function los(x,y){let d=Math.hypot(x-p.x,y-p.y),n=Math.ceil(d*12);for(let i=1;i<n;i++)if(wall(p.x+(x-p.x)*i/n,p.y+(y-p.y)*i/n))return false;return true}
function draw(){
const horizon=H*.51+(state==='play'?Math.sin(step)*H*.005:0);const ceiling=ctx.createLinearGradient(0,0,0,horizon);ceiling.addColorStop(0,'#080c09');ceiling.addColorStop(1,'#23261a');ctx.fillStyle=ceiling;ctx.fillRect(0,0,W,horizon);const floor=ctx.createLinearGradient(0,horizon,0,H);floor.addColorStop(0,'#10130c');floor.addColorStop(1,'#34372b');ctx.fillStyle=floor;ctx.fillRect(0,horizon,W,H);drawFloor(horizon);
for(let x=0;x<W;x+=2){const a=p.a+Math.atan((x/W*2-1)*Math.tan(fov/2)),hit=cast(a),d=hit.d*Math.cos(a-p.a),height=Math.min(H*5,H/d*.8),top=horizon-height/2;zbuf[x>>1]=d;let light=(.16+.95/(1+d*.31))*((1-Math.abs(x/W-.5)*.65))*(hit.side?.76:1);if(wallPhoto.complete&&wallPhoto.naturalWidth){ctx.drawImage(wallPhoto,Math.min(wallPhoto.width-1,Math.floor(hit.u*wallPhoto.width)),0,1,wallPhoto.height,x,top,2,height);ctx.fillStyle=`rgba(0,0,0,${Math.max(.08,1-light*.95)})`;ctx.fillRect(x,top,2,height)}else{ctx.fillStyle=`rgb(${85*light},${80*light},${65*light})`;ctx.fillRect(x,top,2,height)}ctx.fillStyle='#070805';ctx.fillRect(x,top+height*.98,2,height*.02)}

const sprites=objects.filter(o=>!collected.has(o.id)).map(o=>({...o,enemy:false}));if(awake&&!explore)sprites.push({...enemy,type:'enemy',enemy:true});sprites.sort((a,b)=>Math.hypot(b.x-p.x,b.y-p.y)-Math.hypot(a.x-p.x,a.y-p.y));for(const o of sprites){let a=Math.atan2(o.y-p.y,o.x-p.x)-p.a;while(a>Math.PI)a-=Math.PI*2;while(a< -Math.PI)a+=Math.PI*2;if(Math.abs(a)>1.05)continue;let dist=Math.hypot(o.x-p.x,o.y-p.y),d=dist*Math.cos(a);if(d<.1)continue;let sx=W/2+Math.tan(a)/Math.tan(fov/2)*W/2,scale=H/d*.8,ww=scale*(o.enemy?.82:o.type==='exit'?.65:.26),hh=scale*(o.enemy?.9:o.type==='exit'?.98:.22),top=horizon-hh/2+(o.type==='exit'||o.enemy?0:scale*.12);for(let x=Math.max(0,Math.floor(sx-ww/2));x<Math.min(W,sx+ww/2);x++){if(d>zbuf[Math.floor(x/2)]+.1)continue;const u=(x-(sx-ww/2))/ww;if(o.enemy){if(ghostPhoto.complete&&ghostPhoto.naturalWidth){ctx.drawImage(ghostPhoto,Math.min(ghostPhoto.width-1,Math.floor(u*ghostPhoto.width)),0,1,ghostPhoto.height,x,top,1,hh)}else{ctx.fillStyle='#11130f';ctx.fillRect(x,top,1,hh)}}else if(o.type==='exit'){ctx.fillStyle=u<.07||u>.93?'#585e3c':'#171f15';ctx.fillRect(x,top,1,hh);if(u>.72&&u<.8){ctx.fillStyle='#af8f56';ctx.fillRect(x,top+hh*.54,1,hh*.04)}}else{ctx.fillStyle=o.type==='key'?'#b8a263':o.type==='note'?'#b1ae89':'#272b24';ctx.fillRect(x,top,1,hh);if(o.type==='tape'){ctx.fillStyle='#c1bda0';ctx.fillRect(x,top+hh*.17,1,hh*.25);if(u>.14&&u<.86){ctx.fillStyle='#0c100b';ctx.fillRect(x,top+hh*.56,1,hh*.23)}}}}
if(!o.enemy&&dist<5&&Math.abs(a)<.5&&los(o.x,o.y)){ctx.fillStyle='#d1d8b5';ctx.font=`${Math.max(10,W/80)}px monospace`;ctx.textAlign='center';ctx.fillText(o.type==='tape'?'▣':o.type==='key'?'⚿':o.type==='exit'?'SALIDA':'◇',sx,top-12)}}
const v=ctx.createRadialGradient(W*.5,H*.52,H*.09,W*.5,H*.52,Math.max(W,H)*.65);v.addColorStop(0,'#0000');v.addColorStop(.6,'#0002');v.addColorStop(1,'#000d');ctx.fillStyle=v;ctx.fillRect(0,0,W,H);
if(state==='scare'){ctx.fillStyle='#080807';ctx.fillRect(0,0,W,H);if(scarePhoto.complete&&scarePhoto.naturalWidth){const iw=scarePhoto.width,ih=scarePhoto.height;const shake=reduced?0:Math.sin(scareTime*75)*W*.009;const cropW=iw*.47,cropH=ih*.49,k=Math.max(W/cropW,H/cropH)*1.05;ctx.drawImage(scarePhoto,iw*.48,ih*.25,cropW,cropH,(W-cropW*k)/2+shake,(H-cropH*k)/2,cropW*k,cropH*k)}ctx.fillStyle='rgba(80,10,7,.14)';ctx.fillRect(0,0,W,H)}
}
function tell(t,d=5){$('toast').textContent=t;toastTime=d}
function setupAudio(){try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();if(!master){master=audio.createGain();const limiter=audio.createDynamicsCompressor();limiter.threshold.value=-16;limiter.ratio.value=10;master.connect(limiter);limiter.connect(audio.destination);musicBus=audio.createGain();musicBus.gain.value=.6;musicBus.connect(master);noiseBuffer=audio.createBuffer(1,audio.sampleRate*2,audio.sampleRate);const a=noiseBuffer.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=Math.random()*2-1;for(const hz of [49.85,50.15,100.2]){const osc=audio.createOscillator(),g=audio.createGain();osc.type='sine';osc.frequency.value=hz;g.gain.value=.023;osc.connect(g);g.connect(musicBus);osc.start()}}master.gain.setTargetAtTime(sound?.58:0,audio.currentTime,.1);return true}catch{return false}}
function playTone(freq,duration=.15,vol=.06,type='sine',delay=0,bus=null){if(!sound||!audio||!master)return;const t=audio.currentTime+delay,o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(Math.max(.002,vol),t+.012);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(bus||master);o.start(t);o.stop(t+duration+.05)}
function noise(duration=.3,volume=.1,freq=800){if(!sound||!audio||!noiseBuffer)return;const src=audio.createBufferSource(),filter=audio.createBiquadFilter(),g=audio.createGain();src.buffer=noiseBuffer;filter.type='lowpass';filter.frequency.value=freq;g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);src.connect(filter);filter.connect(g);g.connect(master);src.start();src.stop(audio.currentTime+duration)}
function toggleSound(){sound=!sound;if(!setupAudio())sound=false;$('sound').textContent=sound?'MÚSICA ON':'MÚSICA OFF';$('sound').setAttribute('aria-label',sound?'Silenciar música y efectos':'Activar música y efectos');$('sound').setAttribute('aria-pressed',String(sound))}
function setAudioPause(paused){if(master)master.gain.setTargetAtTime(sound?(paused?0:.58):0,audio.currentTime,.12)}
function spatialBus(pan=0){if(audio.createStereoPanner){const b=audio.createStereoPanner();b.pan.value=pan;b.connect(master);return b}const b=audio.createGain();b.connect(master);return b}
function texturedNoise(duration,volume,freq,pan=0,delay=0,type='lowpass'){if(!sound||!audio||!noiseBuffer)return;const t=audio.currentTime+delay,src=audio.createBufferSource(),filter=audio.createBiquadFilter(),g=audio.createGain(),bus=spatialBus(pan);src.buffer=noiseBuffer;filter.type=type;filter.frequency.value=freq;filter.Q.value=.7;g.gain.setValueAtTime(.001,t);g.gain.linearRampToValueAtTime(volume,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+duration);src.connect(filter);filter.connect(g);g.connect(bus);src.start(t);src.stop(t+duration+.02);src.onended=()=>{src.disconnect();filter.disconnect();g.disconnect();bus.disconnect()}}
function spatialTone(hz,duration,volume,pan=0,delay=0,type='sine',endHz=null){if(!sound||!audio)return;const t=audio.currentTime+delay,o=audio.createOscillator(),g=audio.createGain(),bus=spatialBus(pan);o.type=type;o.frequency.setValueAtTime(hz,t);if(endHz)o.frequency.exponentialRampToValueAtTime(endHz,t+duration);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(volume,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(bus);o.start(t);o.stop(t+duration+.02);o.onended=()=>{o.disconnect();g.disconnect();bus.disconnect()}}
function footstep(running=false,pan=null,delay=0,volume=1){const side=pan??((footSide*=-1)*.23);const pitch=62+Math.random()*16;spatialTone(pitch,.17,.23*volume,side,delay,'sine',36);texturedNoise(.1,.20*volume,950,side,delay);texturedNoise(.15,.065*volume,1800,side,delay+.09);spatialTone(135+Math.random()*30,.12,.055*volume,side,delay+.065,'triangle')}
function ambientPad(hz,pan){if(!sound||!audio)return;const t=audio.currentTime;for(const detune of [-.13,.14]){const o=audio.createOscillator(),g=audio.createGain(),bus=spatialBus(pan);o.type='sine';o.frequency.value=hz+detune;g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.047,t+2.5);g.gain.exponentialRampToValueAtTime(.001,t+8);o.connect(g);g.connect(bus);o.start();o.stop(t+8.1);o.onended=()=>{o.disconnect();g.disconnect();bus.disconnect()}}}
function distraction(){const pan=(Math.random()>.5?1:-1)*(.5+Math.random()*.45),kind=Math.floor(Math.random()*5);if(kind===0){for(let i=0;i<3;i++){spatialTone(78,.22,.13,pan,i*.26,'triangle',35);texturedNoise(.12,.09,700,pan,i*.26)}}else if(kind===1){spatialTone(260,1.6,.07,pan,0,'sawtooth',85);texturedNoise(1.4,.035,900,pan,0,'bandpass')}else if(kind===2){for(let i=0;i<4;i++)footstep(false,pan,i*.46,.42)}else if(kind===3){texturedNoise(.65,.11,1600,pan,0,'bandpass');spatialTone(680,.9,.024,pan,.12,'sine',340)}else{for(const hz of [293,417,631])spatialTone(hz,1.3,.06,pan,0,'sine');texturedNoise(.1,.15,2700,pan)}}
function score(dt){if(!sound||!audio)return;musicClock-=dt;if(musicClock<=0){const chord=[[130.81,155.56,196],[123.47,146.83,196],[116.54,155.56,185],[130.81,164.81,207.65]][musicBeat%4];chord.forEach((hz,i)=>ambientPad(hz,(i-1)*.55));texturedNoise(2,.018,380,0,0,'lowpass');if(chasing){playTone(49,.5,.14);playTone(51,.9,.08,'sine',.28)}musicBeat++;musicClock=chasing?2:5.5}distractionClock-=dt;if(distractionClock<=0){distraction();distractionClock=7+Math.random()*10}}
function enemyVoiceCue(){const d=Math.hypot(enemy.x-p.x,enemy.y-p.y),visible=los(enemy.x,enemy.y);let a=Math.atan2(enemy.y-p.y,enemy.x-p.x)-p.a;const pan=Math.sin(a)*.8;const volume=Math.max(.013,.24/(1+d*.55))*(visible?1:.65);return {distance:d,pan,volume,interval:Math.min(6.5,2.2+d*.38)}}
function enemyShriek(){if(!sound||!audio)return;const cue=enemyVoiceCue();const pitch=360+Math.random()*60;spatialTone(pitch,1.05,cue.volume,cue.pan,0,'sawtooth',pitch*.54);spatialTone(pitch*1.48,.95,cue.volume*.37,cue.pan,.06,'triangle',pitch*.91);spatialTone(95,1.2,cue.volume*.48,cue.pan,0,'sawtooth',54);texturedNoise(.9,cue.volume*.7,1700,cue.pan,.025,'bandpass')}
function wake(){if(explore||awake)return;awake=true;chasing=true;safe=2.5;shriekClock=.4;const candidates=[];for(let y=1;y<14;y++)for(let x=1;x<14;x++){const d=Math.hypot(x+.5-p.x,y+.5-p.y);if(!wall(x+.5,y+.5)&&d>=3&&d<5&&los(x+.5,y+.5))candidates.push({x:x+.5,y:y+.5})}enemy=candidates.length?candidates.sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0]:{x:7.5,y:5.5};path=[];pathClock=0;tell('TE HA OÍDO. Corre y pierde su rastro.');playTone(73,1,.18,'sawtooth');noise(.8,.18,950)}
function jumpScare(fatal=false){if(explore)return;state='scare';scareTime=fatal?1.35:.72;scareFatal=fatal;keys={};$('hud').hidden=true;noise(.9,.35,2400);playTone(116,.8,.15,'sawtooth');playTone(123,.75,.12,'sawtooth');playTone(46,1,.3)}
function start(){collected=new Set();fear=0;elapsed=0;safe=2;step=0;awake=false;chasing=false;chaseLost=0;stamina=100;pendingScare=false;scareTime=0;musicBeat=0;musicClock=0;ambushAt=18;distractionClock=5+Math.random()*3;footClock=0;shriekClock=1;document.body.classList.remove('reading');p={x:7.5,y:3.4,a:Math.PI/2};enemy={x:13.5,y:13.5};path=[];pathClock=0;keys={};explore=$('explore').checked;state='play';if(!audio&&!sound)toggleSound();$('intro').hidden=true;$('ending').hidden=true;$('hud').hidden=false;setAudioPause(false);tell('Busca las cintas. Acércate a los objetos y pulsa E para investigar.',7);updateHUD()}
function openDialog(tag,title,body){if(state!=='play')return;state='paused';keys={};look=null;document.body.classList.add('reading');setAudioPause(true);$('dialogtag').textContent=tag;$('dialogtitle').textContent=title;$('dialogbody').innerHTML=body;$('modal').showModal()}
function resume(){if($('modal').open)$('modal').close();if(state==='paused'){state='play';keys={};look=null;safe=Math.max(safe,3);document.body.classList.remove('reading');setAudioPause(false);if(pendingScare){pendingScare=false;wake();jumpScare(false)}}}
function investigate(){if(state!=='play'||!near)return;const o=near;if(o.type==='tape'){collected.add(o.id);playTone(320,.3);openDialog('EVIDENCIA RECUPERADA',o.name,`<p>${o.text}</p><p class="hint">${o.hint}</p>`);if(!explore){if(objects.filter(q=>q.type==='tape'&&collected.has(q.id)).length===1)pendingScare=true;else{safe=Math.max(safe,1.2);chasing=true;}}updateHUD()}else if(o.type==='key'){collected.add(o.id);playTone(680,.2);tell('Tienes la llave. La salida está en el pasillo norte.',6);updateHUD()}else if(o.type==='note'){openDialog('NO ESTÁS SOLO',o.name,'<p>«Las cintas están en los extremos de la casa. La llave, al sureste. La salida, al norte.»</p><p>«La presencia no atraviesa las paredes. Corre para alejarte y dobla las esquinas. Si te pierde de vista durante unos segundos, dejará de correr. Recupera el aliento antes de volver a esprintar.»</p><p class="hint">WASD: avanzar, retroceder y desplazarte a los lados. Flechas: avanzar, retroceder y girar. Arrastra la vista para mirar. Mayús: correr. J: pistas. Esc: pausa.</p>')}else{if(!collected.has('key')){tell('Cerrada. Necesitas la llave que está al sureste de la casa.');return}openDialog('ÚLTIMA OPORTUNIDAD','El código de la puerta','<p>Tres números. En el orden de las cintas.</p><form class="codeform" id="codeform"><input id="code" aria-label="Código de tres cifras" inputmode="numeric" pattern="[0-9]{3}" maxlength="3" autocomplete="off" placeholder="···" required><button type="submit">ABRIR</button></form><p id="codeerror" class="hint" role="status"></p>');$('codeform').onsubmit=e=>{e.preventDefault();if($('code').value==='739'){if(['t1','t2','t3'].every(id=>collected.has(id))){$('modal').close();end(true)}else $('codeerror').textContent='Faltan cintas. No puedes dejar atrás las pruebas.'}else{$('codeerror').textContent='Código incorrecto. Revisa los números destacados en las pistas.';playTone(80,.3)}};$('code').focus()}}
function journal(){const found=objects.filter(o=>o.type==='tape'&&collected.has(o.id));openDialog('TU INVESTIGACIÓN','Las pruebas',found.map(o=>`<p><strong>${o.name}</strong><br>${o.text}</p>`).join('')+(found.length?'':'<p>Todavía no has encontrado ninguna cinta.</p>')+'<p class="hint">Cinta 01: noroeste · Cinta 02: noreste · Cinta 03: suroeste<br>Llave: sureste · Salida: norte<br>El norte es la parte superior del plano.</p>'+mapHTML())}
function mapHTML(){let out='<pre style="font-size:12px;line-height:1.15;letter-spacing:3px;color:#a8b492;background:#0b0e09;padding:15px;width:max-content;max-width:100%;overflow:auto" aria-label="Plano de la casa; tú eres el círculo blanco">';for(let y=0;y<grid.length;y++){for(let x=0;x<grid[0].length;x++){let obj=objects.find(o=>Math.floor(o.x)===x&&Math.floor(o.y)===y&&!collected.has(o.id));out+=Math.floor(p.x)===x&&Math.floor(p.y)===y?'●':grid[y][x]==='1'?'█':obj?.type==='tape'?'T':obj?.type==='key'?'K':obj?.type==='exit'?'S':'·'}out+='\n'}return out+'</pre><p class="hint">● Tú · T Cinta · K Llave · S Salida</p>'}
function updateHUD(){$('tapes').textContent='▣ '+objects.filter(o=>o.type==='tape'&&collected.has(o.id)).length+' / 3';$('key').textContent=collected.has('key')?'⚿ LLAVE':'⚿ SIN LLAVE';$('key').style.color=collected.has('key')?'#debd78':'';$('objective').textContent=collected.size>=4&&collected.has('key')?'VUELVE A LA SALIDA · PASILLO NORTE':'RECUPERA LAS TRES CINTAS';}
function findPath(){let ex=Math.floor(enemy.x),ey=Math.floor(enemy.y),px=Math.floor(p.x),py=Math.floor(p.y),q=[[ex,ey]],seen=new Set([ex+','+ey]),prev={};for(let i=0;i<q.length;i++){const [x,y]=q[i];if(x===px&&y===py)break;for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){let nx=x+dx,ny=y+dy,k=nx+','+ny;if(!wall(nx+.5,ny+.5)&&!seen.has(k)){seen.add(k);prev[k]=[x,y];q.push([nx,ny])}}}let cur=[px,py],arr=[];while(cur[0]!==ex||cur[1]!==ey){arr.unshift({x:cur[0]+.5,y:cur[1]+.5});cur=prev[cur.join(',')];if(!cur)return[]}return arr}
function end(win){state=win?'won':'lost';keys={};$('hud').hidden=true;$('ending').hidden=false;$('endtag').textContent=win?'FIN DE LA GRABACIÓN / SUPERVIVIENTE':'SEÑAL PERDIDA / ARCHIVO CORRUPTO';$('endtitle').innerHTML=win?'HAS SALIDO.<br><span>¿VERDAD?</span>':'AHORA<br><span>ERES PARTE.</span>';$('endtext').textContent=win?'La puerta se abre. El aire vuelve a tus pulmones. En tu bolsillo hay una cuarta cinta. No estaba ahí antes.':'La cámara sigue grabando. Pero ya no eres tú quien la sostiene.';$('endstats').textContent=`Tiempo: ${formatTime(elapsed)} · Cintas: ${objects.filter(o=>o.type==='tape'&&collected.has(o.id)).length}/3${explore?' · Sin persecución':''}`;$('danger').style.opacity=0;setAudioPause(true);playTone(win?220:55,1,.12)}
function formatTime(t){let s=Math.floor(t);return '00:'+String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function update(dt){if(state!=='play'||$('modal').open)return;elapsed+=dt;safe-=dt;if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').textContent=''}let turn=(keys.ArrowRight?1:0)-(keys.ArrowLeft?1:0);p.a+=turn*dt*1.9;let forward=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0),strafe=(keys.KeyD?1:0)-(keys.KeyA?1:0),norm=Math.max(1,Math.hypot(forward,strafe));const running=(keys.ShiftLeft||keys.ShiftRight)&&stamina>2&&(forward||strafe);let speed=running?3.4:1.9;stamina=Math.max(0,Math.min(100,stamina+dt*(running?-25:16)));$('staminabar').style.width=stamina+'%';score(dt);footClock-=dt;if((forward||strafe)&&footClock<=0){footstep(running);footClock=running?.26:.46;}move(p,(Math.cos(p.a)*forward-Math.sin(p.a)*strafe)*speed*dt/norm,(Math.sin(p.a)*forward+Math.cos(p.a)*strafe)*speed*dt/norm);if(forward||strafe)step+=dt*10;
if(!awake&&!explore&&elapsed>=ambushAt)wake();
if(awake&&!explore){shriekClock-=dt;if(shriekClock<=0){enemyShriek();shriekClock=enemyVoiceCue().interval}}
if(awake&&!explore&&safe<=0){const visible=los(enemy.x,enemy.y),dist=Math.hypot(p.x-enemy.x,p.y-enemy.y);if(visible&&dist<7){if(!chasing){tell('TE HA VISTO. ¡CORRE!',3);playTone(110,.6,.12,'sawtooth')}chasing=true;chaseLost=0}else chaseLost+=dt;if(chaseLost>5&&dist>4.5&&chasing){chasing=false;tell('Has perdido su rastro. Sigue buscando.',3)}
let target;if(visible)target=p;else{if(!path.length){path=findPath()}target=path[0]}
if(target){let dx=target.x-enemy.x,dy=target.y-enemy.y,d=Math.hypot(dx,dy);if(d<.08)path.shift();else{let s=Math.min(d,dt*(chasing?1.45:.65));move(enemy,dx/d*s,dy/d*s,.14)}}
fear=Math.max(0,Math.min(100,fear+dt*(dist<1&&visible?85:dist<3&&visible?12:-16)));if(dist<.58&&visible||fear>=100){jumpScare(true);return}heartbeat-=dt;if(dist<5&&heartbeat<=0){playTone(55,.12,.14);heartbeat=dist<2?.4:.75}
}else fear=Math.max(0,fear-dt*15);
$('chase').hidden=!chasing||!awake||explore;

$('danger').style.opacity=fear/150;$('fearbar').style.width=fear+'%';$('bpm').textContent=Math.floor(72+fear*.9);$('timer').textContent=formatTime(elapsed);$('room').textContent=p.y<4?(p.x<6?'SALÓN':p.x>10?'COMEDOR':'PASILLO NORTE'):p.y>10?(p.x<6?'DORMITORIO':'CUARTO DE SERVICIO'):'PASILLO CENTRAL';near=objects.filter(o=>!collected.has(o.id)&&Math.hypot(o.x-p.x,o.y-p.y)<1.45&&los(o.x,o.y)).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0]||null;$('interact').hidden=!near;if(near)$('interact').querySelector('span').textContent=near.name;
}
function frame(t){let dt=Math.min(.04,(t-last)/1000||.016);last=t;if(state==='play')update(dt);else if(state==='scare'){scareTime-=dt;if(scareTime<=0){if(scareFatal)end(false);else{state='play';$('hud').hidden=false;safe=2.5;tell('NO ESTÁS SOLO. Mantén Mayús o CORRER para escapar.',5)}}}draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
$('start').onclick=start;$('restart').onclick=start;$('sound').onclick=toggleSound;$('interact').onclick=investigate;$('journal').onclick=journal;$('pause').onclick=()=>openDialog('GRABACIÓN EN PAUSA','Respira.','<p>La casa puede esperar.</p><p class="hint">Recupera las tres cintas, encuentra la llave y vuelve a la salida. Consulta las pistas para ver el plano y las evidencias recogidas.</p>');$('close').onclick=resume;$('modal').addEventListener('cancel',e=>{e.preventDefault();resume()});
addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(state==='play'){keys[e.code]=true;if(!e.repeat){if(e.code==='KeyE'||e.code==='Space')investigate();if(e.code==='KeyJ')journal();if(e.code==='Escape')$('pause').click()}}});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('blur',()=>{keys={};if(state==='play')$('pause').click()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='play')$('pause').click()});
canvas.addEventListener('pointerdown',e=>{if(state!=='play')return;look={id:e.pointerId,x:e.clientX};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(look?.id===e.pointerId&&state==='play'){p.a+=(e.clientX-look.x)*.006;look.x=e.clientX}});canvas.addEventListener('pointerup',()=>look=null);canvas.addEventListener('pointercancel',()=>look=null);
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();if(state!=='play')return;keys[b.dataset.key]=true;b.setPointerCapture(e.pointerId)});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys[b.dataset.key]=false)}
if(document.modelContext?.registerTool){for(const tool of [{name:'read_game_state',description:'Read the current Dead Home game state and collected clues.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({state,elapsed:Math.floor(elapsed),collected:[...collected],position:{x:p.x,y:p.y},fear:Math.round(fear),pursuit:chasing,stamina:Math.round(stamina)})},{name:'pause_game',description:'Pause the current game and display the pause dialog.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{if(state!=='play')return {error:'Game is not running'};$('pause').click();return {state}}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}}
